### ISSUE TITLE
IP Bazlı istekler göndermek yanıltabilir

### ISSUE THREAD

**Issue by hakandemiral** [yns40/ping_test_tool#1]
AWS datacenter pingleri için ip havuzlarını bulup birkaç tanesine birden istek atıp ve ortalamalarını gösterebilirsin, diğer servislerin domain adreslerini bulup istek atmalısın çoğu dns üzerinde geolocation yük dengelemesi yapıyor çok daha sağlıklı sonuç verecektir.

**Comment by C4LOX** [comment]
Yorumun için çok sağol bat üzerinden yapılabilecek bir şey ise yapabilirim bunu yapabilirim.
